### PR TITLE
Update OWNERS

### PR DESCRIPTION
**Pull request by enj**
Signed-off-by: Monis Khan <mkhan@redhat.com>

### CODE REVIEW

**Comment by spadgett** [comment]
/hold
CI is broken

> level=fatal msg="failed to fetch Terraform Variables: failed to load asset \"Install Config\": failed to upconvert install config: cannot upconvert from version v1"

**Comment by spadgett** [comment]
The bot doesn't want you to leave, Mo :'(

**Comment by bparees** [comment]
hopefully fixing the job here: 
https://github.com/openshift/release/pull/5479

**Comment by bparees** [comment]
hopefully https://github.com/openshift/release/pull/5480 is the last piece of this.

**Pull request merged**
