### PR TITLE
Bug 1932487: Add CVO cluster-profile annotations

### PR DESCRIPTION
**Pull request by vrutkovs**
Include the annotation so that CVO would pick this manifest when cluster-profile is selected

### CODE REVIEW

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by vrutkovs** [comment]
Verified that the configmap is now being applied correctly

**Comment by vrutkovs** [comment]
/hold

Waiting for alert fix to land

**Comment by vrutkovs** [comment]
Fix for baremetal error merged
/hold cancel

**Pull request merged**
